name: Update movie-box gist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  watch:
    types: [started]
  
jobs:
  build:
    name: Updating movie-box gist
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: npm install
      - name: Update
        uses: ./
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          TRAKT_ID: ${{ secrets.TRAKT_ID }}
          TRAKT_USERNAME: ${{ secrets.TRAKT_USERNAME }}
          MOVIE_BOX_MODE: ${{ secrets.MOVIE_BOX_MODE }}
